services:
  db:
    image: postgres:15-alpine
    container_name: mini-heroku-db
    restart: always
    environment:
      POSTGRES_USER: julio
      POSTGRES_PASSWORD:  senha123
      POSTGRES_DB: mini-heroku
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data

  heroku-backend:
    build: ./backend
    container_name: heroku-backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db

volumes:
  postgres_db:
      